FROM python:3.10.0-buster

RUN apt-get update \
 && apt-get install -y curl

RUN pip3 install requests

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

COPY Client.py Client.py
COPY run_client.sh run_client.sh
CMD ./run_client.sh
